# fly.toml app configuration file generated for ai-report-generator
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-report-generator'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/"
    protocol = "http"